name: Deploy Ruby CodeStyle

on:
  push:
    branches:
      - main
    paths:
      - ruby/**

jobs:
  build:
    name: Ruby ${{matrix.ruby}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-16, windows-latest]
        ruby: ["2.5", "2.7", "3.0", "3.1"]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{ github.workspace }}/ruby
          ruby-version: ${{ matrix.ruby }}
          run: gem install bundler
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run RuboCop
        working-directory: ${{ github.workspace }}/ruby
        run: |
          bundle exec rubocop -c .rubocop.yml --force-exclusion --require rubocop-rake
      - name: Run Tests
        working-directory: ${{ github.workspace }}/ruby
        run: | # add more tests as necessary in rake file. Make sure they pass before PR
          bundle exec rake
      